# Generated by Django 4.2.1 on 2023-05-22 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('discount_amount', models.FloatField()),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('patterns', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mktbot_api.coupon')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mktbot_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('redemption_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('redemption_date', models.DateField()),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mktbot_api.coupon')),
            ],
        ),
    ]
