# Generated by Django 4.2.1 on 2023-05-24 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mktbot_api', '0002_auto_20230523_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Intent',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='coupon_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='redemption',
            old_name='redemption_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='redemption',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mktbot_api.user'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='coupon_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mktbot_api.coupon'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mktbot_api.user'),
        ),
    ]
